# Generated by Django 5.2.5 on 2025-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='slideshow/', verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='titulo')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alternative')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'SlideShow',
                'verbose_name_plural': 'SlideShow',
                'ordering': ('titulo',),
            },
        ),
    ]
