# Generated by Django 5.2.5 on 2025-08-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mestre',
        ),
    ]
