# Generated by Django 5.2.5 on 2025-09-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='eh_jogador',
            field=models.BooleanField(default=True),
        ),
    ]
