# Generated by Django 5.2.6 on 2025-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_apelido_remove_usuario_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
