# Generated by Django 5.2.6 on 2025-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=50, verbose_name='personagem')),
                ('avatar_personagem', models.ImageField(upload_to='', verbose_name='avatar')),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='raça')),
                ('classe', models.CharField(blank=True, max_length=100, null=True, verbose_name='classe')),
                ('historia', models.TextField(blank=True, null=True, verbose_name='historia')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ('nome_personagem',),
            },
        ),
    ]
