# Generated by Django 5.2.6 on 2025-09-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0002_personagem_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classe', models.CharField(blank=True, max_length=100, null=True, verbose_name='classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ('nome_classe',),
            },
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area_administrativa.classe'),
        ),
    ]
