# Generated by Django 5.2.6 on 2025-09-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0003_classe_alter_personagem_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagens', to='area_administrativa.classe'),
        ),
    ]
