# Generated by Django 5.2.6 on 2025-09-29 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0004_alter_personagem_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campanha', models.CharField(max_length=50, verbose_name='campanha')),
                ('imagem_de_capa', models.ImageField(upload_to='campanhas/', verbose_name='imagem')),
                ('descricao', models.TextField(blank=True, max_length=50, null=True, verbose_name='descricao')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('mestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ('nome_campanha',),
            },
        ),
    ]
